# Generated by Django 3.1.7 on 2021-02-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashos_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trash',
            name='key',
            field=models.CharField(default='gYpqV5DsZtkVbJvj', max_length=16, unique=True, verbose_name='Ключ'),
            preserve_default=False,
        ),
    ]
